/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as TrackServiceRequestIndexRouteImport } from './routes/track-service-request/index'
import { Route as ServiceRequestFormIndexRouteImport } from './routes/service-request-form/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthAccountSetupRouteImport } from './routes/_auth/account-setup'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackServiceRequestIndexRoute =
  TrackServiceRequestIndexRouteImport.update({
    id: '/track-service-request/',
    path: '/track-service-request/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceRequestFormIndexRoute = ServiceRequestFormIndexRouteImport.update({
  id: '/service-request-form/',
  path: '/service-request-form/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountSetupRoute = AuthAccountSetupRouteImport.update({
  id: '/account-setup',
  path: '/account-setup',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof PublicRoute
  '/account-setup': typeof AuthAccountSetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/service-request-form/': typeof ServiceRequestFormIndexRoute
  '/track-service-request/': typeof TrackServiceRequestIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof PublicRoute
  '/account-setup': typeof AuthAccountSetupRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/service-request-form': typeof ServiceRequestFormIndexRoute
  '/track-service-request': typeof TrackServiceRequestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRoute
  '/_auth/account-setup': typeof AuthAccountSetupRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/service-request-form/': typeof ServiceRequestFormIndexRoute
  '/track-service-request/': typeof TrackServiceRequestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/account-setup'
    | '/forgot-password'
    | '/login'
    | '/dashboard/'
    | '/service-request-form/'
    | '/track-service-request/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/account-setup'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/service-request-form'
    | '/track-service-request'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_public'
    | '/_auth/account-setup'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/dashboard/'
    | '/service-request-form/'
    | '/track-service-request/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ServiceRequestFormIndexRoute: typeof ServiceRequestFormIndexRoute
  TrackServiceRequestIndexRoute: typeof TrackServiceRequestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-service-request/': {
      id: '/track-service-request/'
      path: '/track-service-request'
      fullPath: '/track-service-request/'
      preLoaderRoute: typeof TrackServiceRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-request-form/': {
      id: '/service-request-form/'
      path: '/service-request-form'
      fullPath: '/service-request-form/'
      preLoaderRoute: typeof ServiceRequestFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account-setup': {
      id: '/_auth/account-setup'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AuthAccountSetupRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountSetupRoute: typeof AuthAccountSetupRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountSetupRoute: AuthAccountSetupRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ServiceRequestFormIndexRoute: ServiceRequestFormIndexRoute,
  TrackServiceRequestIndexRoute: TrackServiceRequestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
