/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as ServiceRequestFormIndexRouteImport } from './routes/service-request-form/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as FaqsIndexRouteImport } from './routes/faqs/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestFormIndexRoute = ServiceRequestFormIndexRouteImport.update({
  id: '/service-request-form/',
  path: '/service-request-form/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIndexRoute = FaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/': typeof BlogIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/service-request-form/': typeof ServiceRequestFormIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogIndexRoute
  '/faqs': typeof FaqsIndexRoute
  '/login': typeof LoginIndexRoute
  '/service-request-form': typeof ServiceRequestFormIndexRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/': typeof BlogIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/service-request-form/': typeof ServiceRequestFormIndexRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/'
    | '/faqs/'
    | '/login/'
    | '/service-request-form/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/faqs' | '/login' | '/service-request-form' | '/support'
  id:
    | '__root__'
    | '/'
    | '/blog/'
    | '/faqs/'
    | '/login/'
    | '/service-request-form/'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FaqsIndexRoute: typeof FaqsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ServiceRequestFormIndexRoute: typeof ServiceRequestFormIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-request-form/': {
      id: '/service-request-form/'
      path: '/service-request-form'
      fullPath: '/service-request-form/'
      preLoaderRoute: typeof ServiceRequestFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/': {
      id: '/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof FaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  FaqsIndexRoute: FaqsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ServiceRequestFormIndexRoute: ServiceRequestFormIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
