/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ServiceRequestFormIndexRouteImport } from './routes/service-request-form/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSupportIndexRouteImport } from './routes/_public/support/index'
import { Route as PublicFaqsIndexRouteImport } from './routes/_public/faqs/index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRequestFormIndexRoute = ServiceRequestFormIndexRouteImport.update({
  id: '/service-request-form/',
  path: '/service-request-form/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSupportIndexRoute = PublicSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqsIndexRoute = PublicFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login/': typeof LoginIndexRoute
  '/service-request-form/': typeof ServiceRequestFormIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/faqs/': typeof PublicFaqsIndexRoute
  '/support/': typeof PublicSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginIndexRoute
  '/service-request-form': typeof ServiceRequestFormIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/faqs': typeof PublicFaqsIndexRoute
  '/support': typeof PublicSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/login/': typeof LoginIndexRoute
  '/service-request-form/': typeof ServiceRequestFormIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/faqs/': typeof PublicFaqsIndexRoute
  '/_public/support/': typeof PublicSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/service-request-form/'
    | '/blog/'
    | '/faqs/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/service-request-form' | '/blog' | '/faqs' | '/support'
  id:
    | '__root__'
    | '/_public'
    | '/_public/'
    | '/login/'
    | '/service-request-form/'
    | '/_public/blog/'
    | '/_public/faqs/'
    | '/_public/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ServiceRequestFormIndexRoute: typeof ServiceRequestFormIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-request-form/': {
      id: '/service-request-form/'
      path: '/service-request-form'
      fullPath: '/service-request-form/'
      preLoaderRoute: typeof ServiceRequestFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/support/': {
      id: '/_public/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof PublicSupportIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faqs/': {
      id: '/_public/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof PublicFaqsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicFaqsIndexRoute: typeof PublicFaqsIndexRoute
  PublicSupportIndexRoute: typeof PublicSupportIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicFaqsIndexRoute: PublicFaqsIndexRoute,
  PublicSupportIndexRoute: PublicSupportIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ServiceRequestFormIndexRoute: ServiceRequestFormIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
